import Head from "next/head";
import { Inter } from "next/font/google";
import logo from "../../public/logo2.png";
import { SideBar } from "../../components";
import { Flex, Heading, Text } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ismael Rojas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={logo.src} />
      </Head>

      <main>
        <Flex>
          <SideBar />
          <Flex flexDir="column">
            <Heading fontSize={50}>Ismael Rojas</Heading>
            <Text
              as="h1"
              fontSize={180}
              fontWeight="1000"
              color="#59BDB1"
              sx={{
                textShadow: "0 5px 1px  #272727 ,5px 0 1px  #272727,-5px 0 1px  #272727,0 -5px 1px  #272727 ,5px 5px 1px  #272727,-5px -5px 1px  #272727, -5px 5px 1px  #272727,-5px 5px 1px  #272727, 5px -5px 1px  #272727,5px -5px 1px  #272727"
              }}
            >
              Full-Stack
            </Text>
            <Heading as="h1" size="4xl">
              Developer
            </Heading>
          </Flex>
        </Flex>
      </main>
    </>
  );
}
