import Head from "next/head";
import { Inter } from "next/font/google";
import logo from "../../public/Changed_color_no_BG.png";
import { Navbar, CAButton } from "../../components";
import { Flex, Heading, Text } from "@chakra-ui/react";
import style from "./index.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ismael Rojas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={logo.src} />
      </Head>

      <main>
        <Flex className="justify-center">
        <Flex className="flex-col" w="83%">
          <Navbar />
          <Flex flexDir="column" className=" pt-20">
            <Heading
              h="14px"
              fontWeight="100"
              className={style.jaldi}
              color="#fff"
            >
              Ismael Rojas
            </Heading>
            <Flex flexDir="column" justifyContent="space-between">
              <Text
                as="h1"
                className={style.strokeText}
                fontWeight="1000"
                color="#272727"
              >
                Full-Stack
              </Text>
              <Text
                as="h1"
                className={style.fillText}
                fontWeight="800"
                color="#272727"
              >
                Developer
              </Text>
              <Text className={`${style.Text} md:flex hidden`}color="#272727">
                Passionate developer with strong commitment to innovation,
                critical thinking
              </Text>
              <Text className={`${style.Text} md:flex hidden`} color="#272727">
                and lifelong learning
              </Text>
              <Text className={`${style.Text} md:hidden`} color="#272727">
                Passionate developer with strong commitment to innovation,
                critical thinking and lifelong learning
              </Text>
              <Flex className=" md:mt-16 mt-10">
                <CAButton color="#222222" />
              </Flex>
            </Flex>
          </Flex>
        </Flex>
        <Flex h="80vh">

        </Flex>
        </Flex>
      </main>
    </>
  );
}
