import Head from "next/head";
import { Inter } from "next/font/google";
import logo from "../../public/logo2.png";
import { SideBar } from "../../components";
import { Flex, Heading, Text } from "@chakra-ui/react";
import style from "./index.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ismael Rojas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={logo.src} />
      </Head>

      <main>
        <Flex>
          <SideBar />
          <Flex flexDir="column" paddingTop={105} pl={135}>
            <Heading h="14px" fontWeight="100" className={style.jaldi} color="#fff" fontSize={32}>Ismael Rojas</Heading>
            <Flex flexDir="column" h="250px" justifyContent="space-between"  >
              <Text
                as="h1"
                fontSize={145}
                fontWeight="1000"
                color="#272727"
                className={style.strokeText}
              >
                Full-Stack
              </Text>
              <Text
                as="h1"
                className={style.fillText}
                fontSize={165}
                fontWeight="1000"
                color="#272727"
              >
                Developer
              </Text>
            </Flex>
          </Flex>
        </Flex>
      </main>
    </>
  );
}
